# Generated by Django 4.1.2 on 2022-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
